### ISSUE TITLE
Instalation returns error

### ISSUE THREAD

**Issue by radoslavius** [SteKoe/nextcloud-customproperties#1]
Hi,
this module functionality sounds interestly, but infortunatelly I can not install it. Instalation fails with message "Extracted app customproperties has more than 1 folder". Handly installation finished same. Possible error is extra file in release zip "._customproperties".
Thanks

Nextcloud version 18.0.4

**Comment by SteKoe** [comment]
Hi @radoslavius, I am on it. Trying to fix it since yesterday and running into different problems. :)

**Comment by SteKoe** [comment]
On my two test instances of NextCloud (including 18.0.4) the installation now works. Sorry for any inconvenience. Please try to install the app again and close this issue when solved :)

**Comment by radoslavius** [comment]
Thanks, installation now works

**Comment by SteKoe** [comment]
Glad to hear :)
