### ISSUE TITLE
Nore info's at apps.nextcloud.com/apps/customproperties

### ISSUE THREAD

**Issue by blackcrack** [SteKoe/nextcloud-customproperties#10]
Hi,
if you look at 
https://apps.nextcloud.com/apps/customproperties

is there no info, maby could you copy and past your
Readme.md
info's in them of 
apps.nextcloud.com/apps/customproperties

for have a biiit more info's  on appstore at Nextcloud \*s*

big fad thank you :)
best

**Comment by SteKoe** [comment]
Added a biiit more information to the app info  in 2.0.0 ;)
