### ISSUE TITLE
search support

### ISSUE THREAD

**Issue by avangdev** [SteKoe/nextcloud-customproperties#2]
Hi. it would be nice if support properties in search

**Comment by avangdev** [comment]
also support add propertes via api

**Comment by SteKoe** [comment]
I have released v1.0.1 including an Rest-API as documented in README: https://github.com/SteKoe/nextcloud-customproperties#api

**Comment by vwbusguy** [comment]
I see you have a couple of promising commits on a branch for this.  Is there anything I can do to help?  Paired with fulltextsearch + elasticsearch and having this working might make Nextcloud a viable alternative to Alfresco for a lot of users.

**Comment by suhantha** [comment]
> Hi. it would be nice if support properties in search

Adding properties with search is going to be really useful. Not sure is there any limitation on getting this done

**Comment by SteKoe** [comment]
Implemented in 2.0.0.
