### ISSUE TITLE
This directory is unavailable, please check the logs or contact the administrator

### ISSUE THREAD

**Issue by Buexxy** [SteKoe/nextcloud-customproperties#26]
After update to 2.0.0 i become the Error: This directory is unavailable, please check the logs or contact the administrator  when i go to Files!

**Comment by SteKoe** [comment]
Can you please upload the log file from your system for further investigation? TIA.

**Comment by nachoparker** [comment]
there's more reports here, with logs

https://help.nextcloud.com/t/this-directory-is-unavailable-please-check-the-logs-or-contact-the-administrator/118041

**Comment by p92canca** [comment]
I have had the same problem

**Comment by SteKoe** [comment]
Is it possible to update to PHP 7.4? This would solve the issue.

**Comment by SteKoe** [comment]
Okay, I see the problem. I will provide an update compatible to PHP 7.3.

**Comment by nachoparker** [comment]
That is awesome, thanks!!

**Comment by SteKoe** [comment]
Please check if v2.0.2 is working for you. I have downgraded my local setup to PHP 7.3 and the codebase (of course), too.

**Comment by facorazza** [comment]
I've tried v2.0.2 and it fixes the issue

**Comment by SteKoe** [comment]
I am glad to hear that. Sorry for the troubles.

**Comment by markuszeller** [comment]
I could fix it by setting the memcached protocol to binary in the config/config.php file and restart apache2. It looks like a newer update uses spaces in the keys, causing the problem.

```
'memcached_options' => array(
    \Memcached::OPT_COMPRESSION =>          true,
    \Memcached::OPT_LIBKETAMA_COMPATIBLE => true,
    \Memcached::OPT_BINARY_PROTOCOL =>      true,
),
```

**Comment by chamele0n** [comment]
I caught this same error when upgrading from PHP7.3 to PHP7.4, and Nextcloud 23.0.3 to Nextcloud 24.0.2.

I had tried a few others things including verifying that the account that runs the web server has ownership of the user files directories and ran 'occ files:cleanup' and 'occ files:scan -all' to no avail. 

What ended up working was markuszeller's suggestion about adding memcached options setting the binary protocol. Although I'm unsure why this worked and how it will effect my setup. I believe I enabled memcached as part of configuring my reverse proxy. 

I would also add that it seems the client sync software could still access the server, it was just that the webUI would display the error and not allow the directory to list content.

**Comment by adrackg** [comment]
> I could fix it by setting the memcached protocol to binary in the config/config.php file and restart apache2. It looks like a newer update uses spaces in the keys, causing the problem.
> 
> ```
> 'memcached_options' => array(
>     \Memcached::OPT_COMPRESSION =>          true,
>     \Memcached::OPT_LIBKETAMA_COMPATIBLE => true,
>     \Memcached::OPT_BINARY_PROTOCOL =>      true,
> ),
> ```

i was not able to apply this ,  but this helped me `sudo -u www-data php occ files:scan --all`
but i need to disable `  'filelocking.enabled' => false,` in config.php of Nextcloud
